version: "3"

x-logging:
  &default-logging
  options:
    tag: "{{ .ImageName }}|{{ .Name }}"
    max-size: '100m'
    max-file: '3'
  driver: json-file

x-resources:
  &default-resources
  cpus: 0.3
  mem_limit: 500M

x-custom:
  &default-set
  logging: *default-logging
  networks:
    - parking
  <<: *default-resources

services:
  db:
    image: postgres:14.0-alpine3.14
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    <<: *default-set

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.1
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    <<: *default-set

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/home/app/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    <<: *default-set

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:3000"
    environment:
      BACKEND_PREFIX_URL: http://backend
    <<: *default-set
  
  grafana:
    image: grafana/grafana:8.1.3
    container_name: monitoring-grafana
    ports:
      - "3000:3000"
    <<: *default-set

  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: monitoring-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    <<: *default-set

volumes:
  postgres_data:
  prometheus-data:

networks:
  parking:
