openapi: '3.0.2'
info:
  title: BTS.Parking Client Interface API
  version: '1.1.0'

servers:
  - url: http://localhost:8000/api/v1
    description: Local API server for development.

paths:
  # Authorization

  /request-login-link:
    post:
      operationId: requestLoginLink
      summary: Generate a one-time link that will log a user in with their e-mail.
      tags:
        - Authorization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              email: "user@example.com"
      responses:
        '204':
          description: A login link is sent to the e-mail successfully.
        '400':
          description: The provided e-mail is invalid.

  /get-login-code:
    post:
      operationId: getLoginCode
      summary: Temporary endpoint to bypass e-mail and just get a login code.
      tags:
        - Authorization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              email: "user@example.com"
      responses:
        '200':
          description: A login code is returned successfully.
          content:
            application/json:
              schema:
                type: string
              example: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
        '400':
          description: The provided e-mail is invalid.

  /activate-login-link:
    post:
      operationId: activateLoginLink
      summary: Perform authorization by a given one-time login code.
      tags:
        - Authorization
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login_code:
                  type: string
              required:
                - login_code
      responses:
        '204':
          description: Authorization successful.
          headers:
            Set-Cookie:
              description: Authorization token.
              schema:
                type: string
                example: AUTH_TOKEN=<token-value>; Path=/; HttpOnly
        '404':
          description: The link doesn't exist or isn't valid anymore.

  /me:
    get:
      operationId: me
      summary: Return the information about the currently logged in user.
      tags:
        - Authorization
      security:
        - cookieAuth: []
      responses:
        '200':
          description: User information returned successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /logout:
    post:
      operationId: logOut
      summary: Terminate a user's session.
      tags:
        - Authorization
      responses:
        '204':
          description: Session terminated successfully.
          headers:
            Set-Cookie:
              description: Null token to replace any existing one.
              schema:
                type: string
                example: AUTH_TOKEN=None; Path=/; HttpOnly; Expires=Thu, 01 Jan 1970 00:00:00 GMT

  # Booking

  /zones/{zone_id}/spaces:
    get:
      operationId: listSpaces
      summary: List all the spaces in the zone along with the current occupying vehicles.
      tags:
        - Booking
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A listing of parking spaces is obtained successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spaces'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: A non-admin user attempted to access this endpoint.
        '404':
          $ref: '#/components/responses/ZoneDoesNotExist'

  /zones/{zone_id}/free-spaces:
    get:
      operationId: listFreeSpaces
      summary: List the spaces that are available for parking.
      tags:
        - Booking
      responses:
        '200':
          description: A listing of available parking spaces is obtained successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FreeSpaces'
        '404':
          $ref: '#/components/responses/ZoneDoesNotExist'

  /zones/{zone_id}/book:
    post:
      operationId: bookSpace
      summary: Book a parking space.
      tags:
        - Booking
      security:
        - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                space_id:
                  type: integer
                car_id:
                  type: integer
              required:
                - space_id
                - car_id
      responses:
        '204':
          description: Space booked successfully.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/ZoneDoesNotExist'

  /zones/{zone_id}/release:
    post:
      operationId: releaseSpace
      summary: Stop occupying a parking space.
      tags:
        - Booking
      security:
        - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                space_id:
                  type: integer
              required:
                - space_id
      responses:
        '204':
          description: Parking space released successfully.
        '400':
          description: This place isn't booked.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: This place is booked by another user.
        '404':
          $ref: '#/components/responses/ZoneDoesNotExist'

  # Car Management

  /cars:
    get:
      operationId: listCars
      summary: List the saved cars.
      tags:
        - Car Management
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Listing of all added cars of a user.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      operationId: createCar
      summary: Create a new car.
      tags:
        - Car Management
      security:
        - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
            example:
              model: Volkswagen Touareg
              license_number: A000AA
      responses:
        '200':
          description: Car created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: '#/components/schemas/Car'
                required:
                  - id
        '401':
          $ref: '#/components/responses/Unauthorized'

  /cars/{car_id}:
    delete:
      operationId: deleteCar
      summary: Delete a saved car.
      tags:
        - Car Management
      security:
        - cookieAuth: []
      responses:
        '204':
          description: Car deleted successfully.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: This car isn't owned by this user.
        '404':
          description: This car doesn't exist.

components:
  responses:
    Unauthorized:
      description: The request is not authorized.
    ZoneDoesNotExist:
      description: This zone doesn't exist.

  schemas:
    User:
      type: object
      properties:
        email:
          type: string
        is_admin:
          type: boolean
          readOnly: true
      required:
        - email
      example:
        email: "user@example.com"
        is_admin: false

    FreeSpaces:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
        required:
          - id
      example:
        - id: 1
        - id: 2

    Spaces:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          occupying_car_id:
            type: integer
        required:
          - id
      example:
        - id: 1
          occupying_car_id: 15
        - id: 2

    Car:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        model:
          type: string
        license_number:
          type: string
      required:
        - id
        - model
        - license_number
      example:
        id: 1
        model: Volkswagen Touareg
        license_number: A000AA

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: AUTH_TOKEN
