"""create roads for zones, add hourly_rate to zone

Revision ID: 093df057a11c
Revises: 6c6b0bc618ee
Create Date: 2021-11-27 11:54:13.129449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093df057a11c'
down_revision = '6c6b0bc618ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('hourly_rate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'hourly_rate')
    # ### end Alembic commands ###
