"""Fourth migration

Revision ID: 10a9871dcfd1
Revises: 33dcb5bad912
Create Date: 2021-11-13 17:15:31.801936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a9871dcfd1'
down_revision = '33dcb5bad912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1), nullable=False),
    sa.Column('start_x', sa.Integer(), nullable=False),
    sa.Column('start_y', sa.Integer(), nullable=False),
    sa.Column('end_x', sa.Integer(), nullable=False),
    sa.Column('end_y', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=False)
    op.create_index(op.f('ix_cars_email'), 'cars', ['email'], unique=False)
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.alter_column('spaces', 'zone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'spaces', 'zones', ['zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spaces', type_='foreignkey')
    op.alter_column('spaces', 'zone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_email'), table_name='cars')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
