"""Add cookie expire time

Revision ID: 2a21cc79bb10
Revises: a495ca74997f
Create Date: 2021-11-27 07:14:25.036030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a21cc79bb10'
down_revision = 'a495ca74997f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cookie_expire_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cookie_expire_time')
    # ### end Alembic commands ###
