"""empty message

Revision ID: 33a7cd91dfa8
Revises: 559f3fa62d9b
Create Date: 2021-11-02 19:51:41.834209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a7cd91dfa8'
down_revision = '559f3fa62d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cars_id', table_name='cars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cars_id', 'cars', ['id'], unique=False)
    # ### end Alembic commands ###
