"""Third migration

Revision ID: 33dcb5bad912
Revises: b8e94785f6bd
Create Date: 2021-11-13 17:07:17.022131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33dcb5bad912'
down_revision = 'b8e94785f6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
