"""empty message

Revision ID: 3eb19c051cf1
Revises: cc586c0d96d8
Create Date: 2021-11-11 14:38:40.122526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb19c051cf1'
down_revision = 'cc586c0d96d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
