"""db_population

Revision ID: 46f67047616c
Revises: 
Create Date: 2021-12-04 17:50:32.058235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f67047616c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('token_expire_time', sa.Float(), nullable=True),
    sa.Column('cookie', sa.String(length=256), nullable=True),
    sa.Column('cookie_expire_time', sa.Float(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_users_cookie'), 'users', ['cookie'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=False)

    zones_table = op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1), nullable=False),
    sa.Column('start_x', sa.Integer(), nullable=False),
    sa.Column('start_y', sa.Integer(), nullable=False),
    sa.Column('end_x', sa.Integer(), nullable=False),
    sa.Column('end_y', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=False)
    
    cars_table = op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_email'), 'cars', ['email'], unique=False)
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    
    roads_table = op.create_table('roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_x', sa.Integer(), nullable=False),
    sa.Column('start_y', sa.Integer(), nullable=False),
    sa.Column('end_x', sa.Integer(), nullable=False),
    sa.Column('end_y', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roads_id'), 'roads', ['id'], unique=False)
    op.create_index(op.f('ix_roads_zone_id'), 'roads', ['zone_id'], unique=False)
    
    spaces_table = op.create_table('spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_x', sa.Integer(), nullable=False),
    sa.Column('start_y', sa.Integer(), nullable=False),
    sa.Column('end_x', sa.Integer(), nullable=False),
    sa.Column('end_y', sa.Integer(), nullable=False),
    sa.Column('booked_from', sa.DateTime(), nullable=True),
    sa.Column('booked_until', sa.DateTime(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spaces_car_id'), 'spaces', ['car_id'], unique=False)
    op.create_index(op.f('ix_spaces_id'), 'spaces', ['id'], unique=False)
    op.create_index(op.f('ix_spaces_zone_id'), 'spaces', ['zone_id'], unique=False)

    op.bulk_insert(
        users_table, 
        [{
            'email': 'example@gmail.com', 
            'token': None, 
            'token_expire_time': None, 
            'cookie': None, 
            'is_admin': True, 
            'cookie_expire_time': None,
        }]
    )

    op.bulk_insert(
        zones_table, 
        [{
            'id': i, 
            'name': name, 
            'start_x': start_x, 
            'start_y': start_y, 
            'end_x': end_x, 
            'end_y': end_y, 
            'hourly_rate': hourly_rate} 
            for i, name, start_x, start_y, end_x, end_y, hourly_rate in [
                (1,	'A', 2,	2, 98, 64, 15),
                (2,	'B', 2,	68,	98,	130, 15),
                (3,	'C', 114, 2, 210, 64, 15),
                (4,	'D', 114, 68, 210, 130, 15),
            ]
        ]
    )

    op.bulk_insert(
        cars_table,
        [{
            'id': 1, 
            'email': 'example@gmail.com', 
            'model': 'Volkswagen Touareg', 
            'license_number': 'A000AA',
        }]
    )

    op.bulk_insert(
        roads_table,
        [{
            'id': 1, 
            'start_x': 1, 
            'start_y': 25, 
            'end_x': 98,
            'end_y': 37, 
            'zone_id': 1,
        }]
    )

    op.bulk_insert(
        spaces_table, 
        [{
            'id': i, 
            'zone_id': zone_id,
            'number': number,
            'start_x': start_x, 
            'start_y': start_y, 
            'end_x': end_x, 
            'end_y': end_y, 
            'car_id': car_id,
            'booked_from': booked_from, 
            'booked_until': booked_until} 
            for i, zone_id, number, start_x, start_y, 
                end_x, end_y, car_id, booked_from, booked_until in [
                (1,	1, 1, 1, 1,	13,	23,	None, None, None),
                (2,	1, 2, 15, 1, 27, 23, None, None, None),
                (3,	1, 3, 29, 1, 41, 23, None, None, None),
                (4,	1, 4, 43, 1, 55, 23, None, None, None),
                (5,	1, 5, 57, 1, 69, 23, None, None, None),
                (6,	1, 6, 71, 1, 83, 23, None, None, None),
                (7,	1, 7, 85, 1, 97, 23, None, None, None),
                (8,	1, 8, 1, 39, 13, 61, None, None, None),
                (9,	1, 9, 15, 39, 27, 61, None,	None, None),
                (10, 1,	10,	29,	39,	41,	61,	None, None, None),
                (11, 1,	11,	43,	39,	55,	61,	None, None,	None),
                (12, 1,	12,	57,	39,	69,	61,	None, None, None),
                (13, 1,	13,	71,	39,	83,	61,	None, None,	None),
                (14, 1,	14,	85,	39,	97,	61,	None, None,	None),
            ]
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spaces_zone_id'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_id'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_car_id'), table_name='spaces')
    op.drop_table('spaces')
    op.drop_index(op.f('ix_roads_zone_id'), table_name='roads')
    op.drop_index(op.f('ix_roads_id'), table_name='roads')
    op.drop_table('roads')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_email'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cookie'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
