"""Second migration

Revision ID: 559f3fa62d9b
Revises: 9ce0301412ad
Create Date: 2021-11-02 19:22:36.515600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559f3fa62d9b'
down_revision = '9ce0301412ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
