"""Revert zone coordinates

Revision ID: 6c6b0bc618ee
Revises: b8d357b162b3
Create Date: 2021-11-27 10:16:21.758489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6b0bc618ee'
down_revision = 'b8d357b162b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('start_x', sa.Integer(), nullable=False))
    op.add_column('zones', sa.Column('start_y', sa.Integer(), nullable=False))
    op.add_column('zones', sa.Column('end_x', sa.Integer(), nullable=False))
    op.add_column('zones', sa.Column('end_y', sa.Integer(), nullable=False))
    op.drop_column('zones', 'height')
    op.drop_column('zones', 'width')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('zones', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('zones', 'end_y')
    op.drop_column('zones', 'end_x')
    op.drop_column('zones', 'start_y')
    op.drop_column('zones', 'start_x')
    # ### end Alembic commands ###
