"""empty message

Revision ID: 6d7c9b9550ea
Revises: 71c5bbf05ef4
Create Date: 2021-11-04 13:42:05.584297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7c9b9550ea'
down_revision = '71c5bbf05ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_expire_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_expire_time')
    # ### end Alembic commands ###
