"""empty message

Revision ID: 71c5bbf05ef4
Revises: bfa6bf3921de
Create Date: 2021-11-04 12:23:58.453008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c5bbf05ef4'
down_revision = 'bfa6bf3921de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('cookie', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.alter_column('cars', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cars', 'license_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'license_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cars', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('users')
    # ### end Alembic commands ###
