"""Fix token length

Revision ID: a495ca74997f
Revises: 10a9871dcfd1
Create Date: 2021-11-13 18:29:02.701454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a495ca74997f'
down_revision = '10a9871dcfd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
