"""Add booked_from, booked_until

Revision ID: b8d357b162b3
Revises: 2a21cc79bb10
Create Date: 2021-11-27 09:13:58.562853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d357b162b3'
down_revision = '2a21cc79bb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaces', sa.Column('booked_from', sa.DateTime(), nullable=True))
    op.add_column('spaces', sa.Column('booked_until', sa.DateTime(), nullable=True))
    op.add_column('zones', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('zones', sa.Column('height', sa.Integer(), nullable=False))
    op.drop_column('zones', 'end_x')
    op.drop_column('zones', 'end_y')
    op.drop_column('zones', 'start_y')
    op.drop_column('zones', 'start_x')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('start_x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('zones', sa.Column('start_y', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('zones', sa.Column('end_y', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('zones', sa.Column('end_x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('zones', 'height')
    op.drop_column('zones', 'width')
    op.drop_column('spaces', 'booked_until')
    op.drop_column('spaces', 'booked_from')
    # ### end Alembic commands ###
