"""Second migration

Revision ID: b8e94785f6bd
Revises: b610a95d6cd9
Create Date: 2021-11-13 16:52:04.432072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e94785f6bd'
down_revision = 'b610a95d6cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cars', 'users', ['email'], ['email'])
    op.create_index(op.f('ix_spaces_car_id'), 'spaces', ['car_id'], unique=False)
    op.create_index(op.f('ix_spaces_id'), 'spaces', ['id'], unique=False)
    op.create_index(op.f('ix_spaces_zone_id'), 'spaces', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'spaces', 'cars', ['car_id'], ['id'])
    op.create_index(op.f('ix_users_cookie'), 'users', ['cookie'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cookie'), table_name='users')
    op.drop_constraint(None, 'spaces', type_='foreignkey')
    op.drop_index(op.f('ix_spaces_zone_id'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_id'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_car_id'), table_name='spaces')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    # ### end Alembic commands ###
