"""empty message

Revision ID: bfa6bf3921de
Revises: 33a7cd91dfa8
Create Date: 2021-11-02 19:54:00.642535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa6bf3921de'
down_revision = '33a7cd91dfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
